bonus:
  service:
    port: 8050
    image:
      name: drstarland/bonus-service
      version: "1.0"
    database:
      name: privileges
      username: program
      password: test

flight:
  service:
    port: 8060
    image:
      name: drstarland/flight-service
      version: "1.0"
    database: 
      name: flights
      username: program
      password: test

ticket:
  service:
    port: 8070
    image:
      name: drstarland/ticket-service
      version: "1.0"
    database: 
      name: tickets
      username: program
      password: test

gateway:
  service:
    port: 8080
    image:
      name: drstarland/gateway-service
      version: "1.0"
    # enviroments:
    #  FlightsService__Host: "http://flight-service:8060"
    isGateway: true