name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and publish images
        timeout-minutes: 10
        run: docker compose build

      - name: Deploy
        run: |
          echo "run deploy"
          echo kubectl config set-cluster cloud_okteto_com-cluster --server="https://146.148.56.200:443" --insecure-skip-tls-verify=true
          kubectl config set-cluster cloud_okteto_com-cluster --server="https://146.148.56.200:443" --insecure-skip-tls-verify=true
          echo kubectl config set-credentials cloud_okteto_com-user --token=${{ secrets.OKTETO_TOKEN }}
          kubectl config set-credentials cloud_okteto_com-user --token=${{ secrets.OKTETO_TOKEN }}
          echo kubectl config set-context default --cluster=cloud_okteto_com-cluster --user=cloud_okteto_com-user --namespace=\"drstarland\"
          kubectl config set-context default --cluster=cloud_okteto_com-cluster --user=cloud_okteto_com-user --namespace="drstarland"
          
          kubectl config use-context default
          echo kubectl get pods
          kubectl get pods
          cd k8s && helm upgrade services ./services-chart
          sleep 45

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"